---
output: github_document
# output: word_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# rintro

<!-- badges: start -->
<!-- badges: end -->

The goal of rintro is to provide links and content for an introduction to R course.

The course was first run in 2021 as a 3 hour session with the following structure:

## Prerequisites

To take this course you must have recent versions of R and RStudio installed.

See here for instructions on how to install R on your computer: https://itsleeds.github.io/rrsrr/introduction.html#installing-r-and-rstudio


Part 1: what R can do 1 hr

- Prerequisites: recap on what you need to use R for transport research (10 minutes)
- Demo of using R for transport research to show what's possible (20 minutes)
- Questions on how to use R for transport research (20 minutes)
- 10 minute break and time to set-up R

Part 2: shared practical session (30 minutes)

- Working all together on R basics: https://itsleeds.github.io/rrsrr/basics.html (15 minutes)
- Working all together on using RStudio: https://itsleeds.github.io/rrsrr/rstudio.html (10 minutes)
- Break and questions (5 minutes)

Part 3: breakout rooms (1 hr 30 minutes)

- Using packages: https://itsleeds.github.io/rrsrr/pkgs.html (30 minutes)
- Manipulating data: filtering and selecting data: https://itsleeds.github.io/rrsrr/data.html#tibbles (30 minutes)
- Spatial data: https://itsleeds.github.io/rrsrr/space.html (30 minutes)



